linters:
  enable-all: true
  disable:
      # deprecated (v1.52.2)
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

      # project too small to be such paranoiac
    - goerr113
    - nlreturn
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl

      # not bad suggestions? disable by nolint comments?
    - testpackage
    - gomnd
    - exhaustruct

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/michurin/minlog)
  funlen: {statements: 150, lines: 150} # parsers are long
  cyclop: {max-complexity: 50}          # and "complex"
  lll:
    line-length: 150
