" Generated by vim-plug
" Tue Mar 19 08:20:47 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = '8ee981b4a91f536f52add291594e89fb6645e451'
silent! let g:plugs['cmp-nvim-lsp'].commit = '5af77f54de1b16c34b23cba810150689a3a90312'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['nvim-cmp'].commit = '04e0ca376d6abdbfc8b52180f8ea236cbfddf782'
silent! let g:plugs['nvim-dap'].commit = 'c1695e500c7d552a0a19953a9aefcc89178fb1af'
silent! let g:plugs['nvim-dap-go'].commit = '64f73400761e2d19459e664a52ea478f3a4420e7'
silent! let g:plugs['nvim-dap-ui'].commit = '13888eb35faaba48efaf49130b83e0d12e042e1b'
silent! let g:plugs['nvim-lspconfig'].commit = '8c1831817d40925d22cd8a555296c44c02fdaaf5'
silent! let g:plugs['nvim-nio'].commit = 'ed70af8ad9d4dafdb55539ed2b4454aac2a2a0c3'
silent! let g:plugs['nvim-treesitter'].commit = '2014f8285e306f4c8a896c7d3af53fdd599e5a4f'
silent! let g:plugs['nvim-treesitter-context'].commit = '2484f58384be24da375558c88402f2998193eff6'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '65ad2eca822dfaec2a3603119ec3cc8826a7859e'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = 'd2a4ffc22d9d38d44edb73da007b3cf43451e9b4'
silent! let g:plugs['plenary.nvim'].commit = 'f7adfc4b3f4f91aab6caebf42b3682945fbc35be'
silent! let g:plugs['telescope-dap.nvim'].commit = '8c88d9716c91eaef1cdea13cb9390d8ef447dbfe'
silent! let g:plugs['telescope.nvim'].commit = 'c816406bd50ade6ec754474f08974154487d417c'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'

PlugUpdate!

