" Generated by vim-plug
" Sat Oct 29 11:10:54 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'c66c379915d68fb52ad5ad1195cdd4265a95ef1e'
silent! let g:plugs['cmp-nvim-lsp'].commit = '78924d1d677b29b3d1fe429864185341724ee5a2'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp-vsnip'].commit = '1ae05c6c867d9ad44bce811056e861e0d5c531cb'
silent! let g:plugs['nvim-cmp'].commit = '9bb8ee6e2d6ab3c8cc53323b79f05886bc722faa'
silent! let g:plugs['nvim-dap'].commit = '3d0d7312bb2a8491eb2927504e5cfa6e81b66de4'
silent! let g:plugs['nvim-dap-go'].commit = 'c2902bb96c45e872d947d7e174775e652439add4'
silent! let g:plugs['nvim-dap-ui'].commit = 'f889edb4f2b7fafa2a8f8101aea2dc499849b2ec'
silent! let g:plugs['nvim-lspconfig'].commit = '2315a397fd5057e3a74a09a240f606af28447ebf'
silent! let g:plugs['nvim-treesitter'].commit = '287ffdccc1dd7ed017d844a4fad069fd3340fa94'
silent! let g:plugs['nvim-treesitter-context'].commit = '0dd5eae6dbf226107da2c2041ffbb695d9e267c1'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '75f5895cc662d61eb919da8050b7a0124400d589'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '13739a5705d9592cbe7da372576363dc8ea5f723'
silent! let g:plugs['plenary.nvim'].commit = '4b7e52044bbb84242158d977a50c4cbcd85070c7'
silent! let g:plugs['telescope-dap.nvim'].commit = 'b4134fff5cbaf3b876e6011212ed60646e56f060'
silent! let g:plugs['telescope.nvim'].commit = '97847309cbffbb33e442f07b8877d20322a26922'
silent! let g:plugs['vim-vsnip'].commit = '03010115eb8bdda00ce5f845cc2f7025700e33bb'

PlugUpdate!

