" Generated by vim-plug
" Wed May 31 22:22:22 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = '5af1bb7d722ef8a96658f01d6eb219c4cf746b32'
silent! let g:plugs['cmp-nvim-lsp'].commit = '0e6b2ed705ddcff9738ec4ea838141654f12eeef'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['nvim-cmp'].commit = 'fc0f694af1a742ada77e5b1c91ff405c746f4a26'
silent! let g:plugs['nvim-dap'].commit = '56118cee6af15cb9ddba9d080880949d8eeb0c9f'
silent! let g:plugs['nvim-dap-go'].commit = 'cdf604a5703838f65fdee7c198f6cb59b563ef6f'
silent! let g:plugs['nvim-dap-ui'].commit = 'c020f660b02772f9f3d11f599fefad3268628a9e'
silent! let g:plugs['nvim-lspconfig'].commit = '9166622781a39a829878d1fd24c174529d996838'
silent! let g:plugs['nvim-treesitter'].commit = '23dfae4db84f71e2ddb56c024845b322035182ee'
silent! let g:plugs['nvim-treesitter-context'].commit = '24535437a9b62b9ec503c545f35e2ac298cd29df'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '65ad2eca822dfaec2a3603119ec3cc8826a7859e'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '95b76b95eff25e1e64f363938cd853852355d70a'
silent! let g:plugs['plenary.nvim'].commit = '52544825d6b8be677eb395983515ad5e30ae1f2e'
silent! let g:plugs['telescope-dap.nvim'].commit = '313d2ea12ae59a1ca51b62bf01fc941a983d9c9c'
silent! let g:plugs['telescope.nvim'].commit = '6d3fbffe426794296a77bb0b37b6ae0f4f14f807'
silent! let g:plugs['vim-vsnip'].commit = '7753ba9c10429c29d25abfd11b4c60b76718c438'

PlugUpdate!

