-- HACKS -- LEGACY MODE -- before any highlight
vim.cmd([[colorscheme vim]])
-- /HACKS

vim.api.nvim_create_autocmd('TextYankPost', {
  group    = vim.api.nvim_create_augroup('highlight_yank', {}),
  desc     = 'Hightlight selection on yank',
  pattern  = '*',
  callback = function()
    vim.highlight.on_yank {higroup = 'Visual', timeout = 500}
  end,
})

vim.api.nvim_set_hl(0, 'TelescopeNormal',   {fg='#c0c0c0'})
vim.api.nvim_set_hl(0, 'TelescopeMatching', {bg='#005f5f', fg='none'})
vim.api.nvim_set_hl(0, 'Pmenu',      {bg='#1c1c1c', fg='#afd7ff'})
vim.api.nvim_set_hl(0, 'PmenuSel',   {bg='#585858', fg='#afd7ff'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultHint',         {bg='#1c1c1c', fg='#5f8700'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultInformation',  {bg='#1c1c1c', fg='#0087af'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultWarning',      {bg='#1c1c1c', fg='#af875f'})
vim.api.nvim_set_hl(0, 'LspDiagnosticsDefaultError',        {bg='#1c1c1c', fg='#af0000'})
vim.api.nvim_set_hl(0, 'TreesitterContext',                 {bg='#444444'})
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber',       {bg='#444444', fg='#ff00d7'})
vim.api.nvim_set_hl(0, 'Whitespace',   {fg='#555555'})
vim.api.nvim_set_hl(0, 'NonText',      {fg='#555555'})
vim.api.nvim_set_hl(0, 'EndOfBuffer',  {fg='#888888'})
vim.api.nvim_set_hl(0, 'LineNr',       {fg='#888888'})
vim.api.nvim_set_hl(0, 'StatusLineNC', {bg='#444444', fg='#000000'})
vim.api.nvim_set_hl(0, 'StatusLine',   {bg='#444444', fg='#ffffff'})
vim.api.nvim_set_hl(0, 'VertSplit',    {fg='#444444'})
vim.api.nvim_set_hl(0, 'TabLine',      {bg='#444444', fg='#000000'})
vim.api.nvim_set_hl(0, 'TabLineSel',   {bg='#444444', fg='#ffffff'})
vim.api.nvim_set_hl(0, 'TabLineFill',  {bg='#444444'})
vim.api.nvim_set_hl(0, 'CursorLine',   {bg='#6c6c6c'})
vim.api.nvim_set_hl(0, 'CursorLineNr', {bg='#6c6c6c'})
vim.api.nvim_set_hl(0, 'CursorColumn', {bg='#6c6c6c'})
vim.api.nvim_set_hl(0, 'Normal',       {})
vim.api.nvim_set_hl(0, 'NormalFloat',  {})
vim.api.nvim_set_hl(0, 'FloatBorder',  {})
vim.api.nvim_set_hl(0, 'Search',       {bg='#005f5f'})
vim.api.nvim_set_hl(0, 'IncSearch',    {bg='#5f5f00'})
vim.api.nvim_set_hl(0, 'Todo',         {fg='#00fafa', bg='#ffff00'})
vim.api.nvim_set_hl(0, 'SpellBad',     {underline=true})
vim.api.nvim_set_hl(0, 'SpellCap',     {underline=true})
vim.api.nvim_set_hl(0, 'SpellRare',    {underline=true})
vim.api.nvim_set_hl(0, 'SpellLocal',   {underline=true})
vim.api.nvim_set_hl(0, 'Folded',       {bg='#262626', fg='#afff5f'})
vim.api.nvim_set_hl(0, 'htmlH1',              {bg='#303030', fg='#ffffff'})
vim.api.nvim_set_hl(0, 'markdownH1Delimiter', {bg='#303030', fg='#ffffff'})
vim.api.nvim_set_hl(0, 'htmlH2',              {bg='#303030', fg='#ffff00'})
vim.api.nvim_set_hl(0, 'markdownH2Delimiter', {bg='#303030', fg='#ffff00'})
vim.api.nvim_set_hl(0, 'htmlH3',              {bg='#303030', fg='#5fff00'})
vim.api.nvim_set_hl(0, 'markdownH3Delimiter', {bg='#303030', fg='#5fff00'})
vim.api.nvim_set_hl(0, 'htmlH4',              {bg='#303030', fg='#00d7ff'})
vim.api.nvim_set_hl(0, 'markdownH4Delimiter', {bg='#303030', fg='#00d7ff'})
vim.api.nvim_set_hl(0, 'htmlH5',              {bg='#303030', fg='#ff87ff'})
vim.api.nvim_set_hl(0, 'markdownH5Delimiter', {bg='#303030', fg='#ff87ff'})
vim.api.nvim_set_hl(0, 'htmlH6',              {bg='#303030', fg='#ffffff'})
vim.api.nvim_set_hl(0, 'markdownH6Delimiter', {bg='#303030', fg='#ffffff'})
vim.api.nvim_set_hl(0, 'htmlLink',            {fg='#5fd7ff'})
vim.api.nvim_set_hl(0, 'markdownCodeBlock',   {fg='#5fafaf'})
vim.api.nvim_set_hl(0, 'markdownCode',        {fg='#5fafaf'})
vim.api.nvim_set_hl(0, 'markdownStrike',      {fg='#5f8787'})
vim.api.nvim_set_hl(0, 'markdownItalic',      {fg='#ffffff'})
vim.api.nvim_set_hl(0, 'SignColumn',          {bg='#1c1c1c', fg='#ff0077'})
