" Generated by vim-plug
" Mon Jun 10 21:58:27 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'd250c63aa13ead745e3a40f61fdd3470efde3923'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['nvim-cmp'].commit = 'a110e12d0b58eefcf5b771f533fc2cf3050680ac'
silent! let g:plugs['nvim-dap'].commit = '6f79b822997f2e8a789c6034e147d42bc6706770'
silent! let g:plugs['nvim-dap-go'].commit = 'a0c5a2b991d7e9304a9a032cf177e22a4b0acda1'
silent! let g:plugs['nvim-dap-ui'].commit = 'b7267003ba4dd860350be86f75b9d9ea287cedca'
silent! let g:plugs['nvim-lspconfig'].commit = '4d38bece98300e3e5cd24a9aa0d0ebfea4951c16'
silent! let g:plugs['nvim-nio'].commit = '7969e0a8ffabdf210edd7978ec954a47a737bbcc'
silent! let g:plugs['nvim-treesitter'].commit = 'eb59a3df509322924631c1ed85b0d2ec696bb78d'
silent! let g:plugs['nvim-treesitter-context'].commit = '5efba33af0f39942e426340da7bc15d7dec16474'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '65ad2eca822dfaec2a3603119ec3cc8826a7859e'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '34867c69838078df7d6919b130c0541c0b400c47'
silent! let g:plugs['plenary.nvim'].commit = 'a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683'
silent! let g:plugs['telescope-dap.nvim'].commit = '8c88d9716c91eaef1cdea13cb9390d8ef447dbfe'
silent! let g:plugs['telescope.nvim'].commit = 'f12b15e1b3a33524eb06a1ae7bc852fb1fd92197'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'

PlugUpdate!

