" Generated by vim-plug
" Sat Sep  7 11:32:42 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'd250c63aa13ead745e3a40f61fdd3470efde3923'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['nvim-cmp'].commit = 'ae644feb7b67bf1ce4260c231d1d4300b19c6f30'
silent! let g:plugs['nvim-dap'].commit = '20a4859ebde1c9bc8e96f8cc11a20667e7fdd516'
silent! let g:plugs['nvim-dap-go'].commit = '5511788255c92bdd845f8d9690f88e2e0f0ff9f2'
silent! let g:plugs['nvim-dap-ui'].commit = '1c351e4e417d4691da12948b6ecf966936a56d28'
silent! let g:plugs['nvim-lspconfig'].commit = 'bdbc65aadc708ce528efb22bca5f82a7cca6b54d'
silent! let g:plugs['nvim-nio'].commit = 'a428f309119086dc78dd4b19306d2d67be884eee'
silent! let g:plugs['nvim-treesitter'].commit = 'ccbaee59547425ef8b766433a6020ac191f3151f'
silent! let g:plugs['nvim-treesitter-context'].commit = 'e6cc783b74606d97ca9eff6494e3f5c2ca603a50'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '65ad2eca822dfaec2a3603119ec3cc8826a7859e'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = 'fe3deb7f67ce0cc4ebfe2ea6c1c7ae1c7a939d73'
silent! let g:plugs['plenary.nvim'].commit = 'ec289423a1693aeae6cd0d503bac2856af74edaa'
silent! let g:plugs['tabnine-nvim'].commit = '3ae92fc4fa8b82bfc70fba9d0741fdb5842e74c1'
silent! let g:plugs['telescope-dap.nvim'].commit = '8c88d9716c91eaef1cdea13cb9390d8ef447dbfe'
silent! let g:plugs['telescope.nvim'].commit = '5972437de807c3bc101565175da66a1aa4f8707a'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'

PlugUpdate!

