" Generated by vim-plug
" Sat Oct 27 00:00:00 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'd250c63aa13ead745e3a40f61fdd3470efde3923'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['nvim-cmp'].commit = '29fb4854573355792df9e156cb779f0d31308796'
silent! let g:plugs['nvim-dap'].commit = '7ff6936010b7222fea2caea0f67ed77f1b7c60dd'
silent! let g:plugs['nvim-dap-go'].commit = '6aa88167ea1224bcef578e8c7160fe8afbb44848'
silent! let g:plugs['nvim-dap-ui'].commit = 'ffa89839f97bad360e78428d5c740fdad9a0ff02'
silent! let g:plugs['nvim-lspconfig'].commit = '4ae8ea049034a4f1b95b3e671ab9d35c16eeafb9'
silent! let g:plugs['nvim-nio'].commit = 'a428f309119086dc78dd4b19306d2d67be884eee'
silent! let g:plugs['nvim-treesitter'].commit = '48fc5d1dfe3dded8028826dfee7526e26212c73b'
silent! let g:plugs['nvim-treesitter-context'].commit = 'e7fdb4cdf0942cd6e63dd822110a93c0ec777fe5'
silent! let g:plugs['nvim-treesitter-refactor'].commit = 'd8b74fa87afc6a1e97b18da23e762efb032dc270'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '3e450cd85243da99dc23ebbf14f9c70e9a0c26a4'
silent! let g:plugs['plenary.nvim'].commit = '2d9b06177a975543726ce5c73fca176cedbffe9d'
silent! let g:plugs['tabnine-nvim'].commit = '3ae92fc4fa8b82bfc70fba9d0741fdb5842e74c1'
silent! let g:plugs['telescope-dap.nvim'].commit = '8c88d9716c91eaef1cdea13cb9390d8ef447dbfe'
silent! let g:plugs['telescope.nvim'].commit = 'df534c3042572fb958586facd02841e10186707c'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'

PlugUpdate!

