linters:
  enable-all: true
  disable:
      # deprecated
    - execinquery
      # disabled because the Go version (1.21)
    - copyloopvar
    - intrange
      # TODO turn on
    - depguard
    - gosec
    - forbidigo
    - typecheck
    - cyclop
    - godot
    - funlen
    - exhaustruct
    - forcetypeassert
    - wrapcheck
    - varnamelen
    - godox
    - paralleltest
    - gomnd
    - gochecknoglobals
    - wsl
    - lll
    - nlreturn
    - wastedassign
    - err113
    - mnd
    - testifylint
    - nestif
    - perfsprint
    - inamedparam
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/michurin/cnbot)

