Section "Monitor"
    Identifier "TCL LCD TV" # 32DD420
    Modeline "1366x768" 75.61 1366 1406 1438 1574 768 771 777 800 -hsync -vsync
    DisplaySize 700 400 # mm
    Option "PreferredMode" "1366x768" # intel drivers do not like this option
EndSection

Section "Screen"
    Identifier "Screen0"
    Monitor "TCL LCD TV"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1366x768" # for intel drivers
        # Modes "1360x768"
    EndSubSection
EndSection
