// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalsService_Square_FullMethodName     = "/api.v1.CalsService/Square"
	CalsService_Sum_FullMethodName        = "/api.v1.CalsService/Sum"
	CalsService_Repeat_FullMethodName     = "/api.v1.CalsService/Repeat"
	CalsService_PipeSquare_FullMethodName = "/api.v1.CalsService/PipeSquare"
)

// CalsServiceClient is the client API for CalsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalsServiceClient interface {
	Square(ctx context.Context, in *Number, opts ...grpc.CallOption) (*Number, error)
	Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Number, Number], error)
	Repeat(ctx context.Context, in *Number, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Number], error)
	PipeSquare(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Number, Number], error)
}

type calsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalsServiceClient(cc grpc.ClientConnInterface) CalsServiceClient {
	return &calsServiceClient{cc}
}

func (c *calsServiceClient) Square(ctx context.Context, in *Number, opts ...grpc.CallOption) (*Number, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Number)
	err := c.cc.Invoke(ctx, CalsService_Square_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calsServiceClient) Sum(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Number, Number], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalsService_ServiceDesc.Streams[0], CalsService_Sum_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Number, Number]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalsService_SumClient = grpc.ClientStreamingClient[Number, Number]

func (c *calsServiceClient) Repeat(ctx context.Context, in *Number, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Number], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalsService_ServiceDesc.Streams[1], CalsService_Repeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Number, Number]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalsService_RepeatClient = grpc.ServerStreamingClient[Number]

func (c *calsServiceClient) PipeSquare(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Number, Number], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalsService_ServiceDesc.Streams[2], CalsService_PipeSquare_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Number, Number]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalsService_PipeSquareClient = grpc.BidiStreamingClient[Number, Number]

// CalsServiceServer is the server API for CalsService service.
// All implementations must embed UnimplementedCalsServiceServer
// for forward compatibility.
type CalsServiceServer interface {
	Square(context.Context, *Number) (*Number, error)
	Sum(grpc.ClientStreamingServer[Number, Number]) error
	Repeat(*Number, grpc.ServerStreamingServer[Number]) error
	PipeSquare(grpc.BidiStreamingServer[Number, Number]) error
	mustEmbedUnimplementedCalsServiceServer()
}

// UnimplementedCalsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalsServiceServer struct{}

func (UnimplementedCalsServiceServer) Square(context.Context, *Number) (*Number, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Square not implemented")
}
func (UnimplementedCalsServiceServer) Sum(grpc.ClientStreamingServer[Number, Number]) error {
	return status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalsServiceServer) Repeat(*Number, grpc.ServerStreamingServer[Number]) error {
	return status.Errorf(codes.Unimplemented, "method Repeat not implemented")
}
func (UnimplementedCalsServiceServer) PipeSquare(grpc.BidiStreamingServer[Number, Number]) error {
	return status.Errorf(codes.Unimplemented, "method PipeSquare not implemented")
}
func (UnimplementedCalsServiceServer) mustEmbedUnimplementedCalsServiceServer() {}
func (UnimplementedCalsServiceServer) testEmbeddedByValue()                     {}

// UnsafeCalsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalsServiceServer will
// result in compilation errors.
type UnsafeCalsServiceServer interface {
	mustEmbedUnimplementedCalsServiceServer()
}

func RegisterCalsServiceServer(s grpc.ServiceRegistrar, srv CalsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalsService_ServiceDesc, srv)
}

func _CalsService_Square_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Number)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalsServiceServer).Square(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalsService_Square_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalsServiceServer).Square(ctx, req.(*Number))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalsService_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalsServiceServer).Sum(&grpc.GenericServerStream[Number, Number]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalsService_SumServer = grpc.ClientStreamingServer[Number, Number]

func _CalsService_Repeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Number)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalsServiceServer).Repeat(m, &grpc.GenericServerStream[Number, Number]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalsService_RepeatServer = grpc.ServerStreamingServer[Number]

func _CalsService_PipeSquare_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalsServiceServer).PipeSquare(&grpc.GenericServerStream[Number, Number]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalsService_PipeSquareServer = grpc.BidiStreamingServer[Number, Number]

// CalsService_ServiceDesc is the grpc.ServiceDesc for CalsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.CalsService",
	HandlerType: (*CalsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Square",
			Handler:    _CalsService_Square_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sum",
			Handler:       _CalsService_Sum_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Repeat",
			Handler:       _CalsService_Repeat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PipeSquare",
			Handler:       _CalsService_PipeSquare_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
