// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalsService_Square_FullMethodName = "/api.v1.CalsService/Square"
)

// CalsServiceClient is the client API for CalsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalsServiceClient interface {
	Square(ctx context.Context, in *Number, opts ...grpc.CallOption) (*Number, error)
}

type calsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalsServiceClient(cc grpc.ClientConnInterface) CalsServiceClient {
	return &calsServiceClient{cc}
}

func (c *calsServiceClient) Square(ctx context.Context, in *Number, opts ...grpc.CallOption) (*Number, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Number)
	err := c.cc.Invoke(ctx, CalsService_Square_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalsServiceServer is the server API for CalsService service.
// All implementations must embed UnimplementedCalsServiceServer
// for forward compatibility.
type CalsServiceServer interface {
	Square(context.Context, *Number) (*Number, error)
	mustEmbedUnimplementedCalsServiceServer()
}

// UnimplementedCalsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalsServiceServer struct{}

func (UnimplementedCalsServiceServer) Square(context.Context, *Number) (*Number, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Square not implemented")
}
func (UnimplementedCalsServiceServer) mustEmbedUnimplementedCalsServiceServer() {}
func (UnimplementedCalsServiceServer) testEmbeddedByValue()                     {}

// UnsafeCalsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalsServiceServer will
// result in compilation errors.
type UnsafeCalsServiceServer interface {
	mustEmbedUnimplementedCalsServiceServer()
}

func RegisterCalsServiceServer(s grpc.ServiceRegistrar, srv CalsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalsService_ServiceDesc, srv)
}

func _CalsService_Square_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Number)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalsServiceServer).Square(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalsService_Square_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalsServiceServer).Square(ctx, req.(*Number))
	}
	return interceptor(ctx, in, info, handler)
}

// CalsService_ServiceDesc is the grpc.ServiceDesc for CalsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.CalsService",
	HandlerType: (*CalsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Square",
			Handler:    _CalsService_Square_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
