[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#666666"
blue = "#4186be"
cyan = "#71bebe"
green = "#c5f779"
magenta = "#cf9ebe"
red = "#cf6171"
white = "#ffffff"
yellow = "#fff796"

[colors.normal]
black = "#000000"
blue = "#414171"
cyan = "#418179"
green = "#aece92"
magenta = "#963c59"
red = "#9e1828"
white = "#bebebe"
yellow = "#968a38"

[colors.primary]
background = "#000000"
foreground = "#bebebe"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Light Italic"

[font.normal]
family = "JetBrains Mono"
style = "Light"

[selection]
semantic_escape_chars = ",│`|\"' ()[]{}<>\t▹·"
save_to_clipboard = true

[window]
startup_mode = "SimpleFullscreen" # MacOS only, use "Fullscreen" for others
dynamic_title = false
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 1
y = 1

[[keyboard.bindings]]
key = "NumpadAdd"
mods = "Alt"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "NumpadSubtract"
mods = "Alt"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "NumpadMultiply"
mods = "Alt"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "NumpadEnter"
mods = "Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]] # linux
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]] # macos
key = "Enter"
mods = "Option"
action = "ToggleSimpleFullscreen"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[[mouse.bindings]]
mouse = "Middle"
mods = "Shift"
action = "Paste"

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

[[mouse.bindings]]
mouse = "Right"
mods = "Shift"
action = "Paste"
