[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#666666"
red = "#cf6171"
green = "#c5f779"
yellow = "#fff796"
blue = "#4186be"
magenta = "#cf9ebe"
cyan = "#71bebe"
white = "#ffffff"

[colors.normal]
black = "#000000"
red = "#9e1828"
green = "#aece92"
yellow = "#968a38"
blue = "#414171"
magenta = "#963c59"
cyan = "#418179"
white = "#bebebe"

[colors.primary]
background = "#000000"
foreground = "#bebebe"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Light Italic"

[font.normal]
family = "JetBrains Mono"
style = "Light"

[selection]
semantic_escape_chars = ",│`|\"' ()[]{}<>\t▹·\\"

[window]
startup_mode = "SimpleFullscreen" # MacOS only, use "Fullscreen" for others
dynamic_title = false
decorations = "Buttonless"
opacity = 0.95
blur = true
option_as_alt = "OnlyRight"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 3
y = 3

[[keyboard.bindings]]
key = "NumpadEnter"
mods = "Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]] # linux
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]] # macos
key = "Enter"
mods = "Command"
action = "ToggleSimpleFullscreen"
