#!/bin/sh -e

VPN_USER='avmichurin'

PASSWD_FILE=passwd.txt

if test -z "$VPN_PASS"
then
    if test -z "$DISPLAY"
    then
        printf '%s' "$(tput setaf 2)$(tput bold)Touch our $(tput rev)yubikey$(tput sgr0) "
        read -r VPN_PASS
        exec "$0"
    else
        VPN_PASS=$(cat <<'CODE' | wish
wm title . "VPN password"
entry .pass -width 50 -show x -textvar pw
bind . <Return> {puts $pw; exit}
bind . <Escape> {exit 1}
pack .pass
focus .pass
CODE
        )
        VPN_PASS="$VPN_PASS" xterm -bg '#002222' -fg '#ffff33' -fs 7 -geometry 100x10 "$0" &
        exit
    fi
fi

echo "$VPN_USER" >$PASSWD_FILE
echo "$VPN_PASS" >>$PASSWD_FILE

# Get update-resolv-conf from:
# wget https://raw.githubusercontent.com/alfredopalhares/openvpn-update-resolv-conf/master/update-resolv-conf.sh -O /etc/openvpn/update-resolv-conf
# Add line like that into sudoers:
# your_user_name ALL=(root) NOPASSWD: /usr/bin/openvpn
# Note:
# OpenVPN will only read passwords from a file if it has been built with the --enable-password-save configure option
sudo openvpn --config client.ovpn --script-security 2 --up /etc/openvpn/update-resolv-conf --down /etc/openvpn/update-resolv-conf --auth-user-pass passwd.txt
