#!/bin/sh

TOKEN=xxx
CHAT=123
TEXT=text

curl "https://api.telegram.org/bot${TOKEN}/sendMessage" -s -F chat_id="$CHAT" -F text="$TEXT"

exit

# how to figure out user and chat ids

curl "https://api.telegram.org/bot${TOKEN}/getUpdates" -s | jq

curl "https://api.telegram.org/bot${TOKEN}/getUpdates" -s | jq .result[].update_id | sort -n | tail -1 # -> $highest_previously_received

OFFSET=$(($highest_previously_received + 1))
curl "https://api.telegram.org/bot${TOKEN}/getUpdates" -s -F offset=$OFFSET -F limit=10 -F timeout=10 | jq

# more info: https://core.telegram.org/bots/api#getupdates
