#!/bin/sh

if test "a$1" = 'a-s'
then
    date
    tmux list-panes -aF '#S'$'\t''#{pane_current_command}'$'\t''#{pane_current_path}'
    exit 0
fi
tmux list-panes -aF $'\033[94m''#S'$'\033[0m'' '$'\033[92m''#{pane_current_command}'$'\033[0m'' '$'\033[93m''#{pane_current_path}'$'\033[0m'
