" Generated by vim-plug
" Sun Jun 12 15:14:36 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '12463cfcd9b14052f9effccbf1d84caa7a2d57f0'
silent! let g:plugs['cmp-cmdline'].commit = 'c36ca4bc1dedb12b4ba6546b96c43896fd6e7252'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
silent! let g:plugs['cmp-path'].commit = '466b6b8270f7ba89abd59f402c73f63c7331ff6e'
silent! let g:plugs['cmp-vsnip'].commit = '0abfa1860f5e095a07c477da940cfcb0d273b700'
silent! let g:plugs['nvim-cmp'].commit = '15c7bf7c0dfb7c75eb526c53f9574633c13dc22d'
silent! let g:plugs['nvim-lspconfig'].commit = '4eac16e87f24ad26738e632446e29766e87141ae'
silent! let g:plugs['nvim-treesitter'].commit = '129082285a5fd0a33fffa328760b906f98d889ef'
silent! let g:plugs['nvim-treesitter-context'].commit = '026e6f407d41f0f8229c067b0a2a19c6ab26bdae'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '75f5895cc662d61eb919da8050b7a0124400d589'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = 'b1e850b77e57b2720c06d523d6fc4776ad6a5608'
silent! let g:plugs['plenary.nvim'].commit = '9c3239bc5f99b85be1123107f7290d16a68f8e64'
silent! let g:plugs['telescope.nvim'].commit = 'e6b69b1488c598ff7b461c4d9cecad57ef708f9b'
silent! let g:plugs['vim-vsnip'].commit = '8f199ef690ed26dcbb8973d9a6760d1332449ac9'

PlugUpdate!

