" Generated by vim-plug
" Sat Oct  1 23:16:08 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'c66c379915d68fb52ad5ad1195cdd4265a95ef1e'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'affe808a5c56b71630f17aa7c38e15c59fd648a8'
silent! let g:plugs['cmp-path'].commit = '447c87cdd6e6d6a1d2488b1d43108bfa217f56e1'
silent! let g:plugs['cmp-vsnip'].commit = '0abfa1860f5e095a07c477da940cfcb0d273b700'
silent! let g:plugs['nvim-cmp'].commit = '2427d06b6508489547cd30b6e86b1c75df363411'
silent! let g:plugs['nvim-dap'].commit = '0b320f5bd4e5f81e8376f9d9681b5c4ee4483c25'
silent! let g:plugs['nvim-dap-go'].commit = 'c2902bb96c45e872d947d7e174775e652439add4'
silent! let g:plugs['nvim-dap-ui'].commit = 'c8ce83a66deb0ca6f5af5a9f9d5fcc05a6d0f66b'
silent! let g:plugs['nvim-lspconfig'].commit = 'af43c300d4134db3550089cd4df6c257e3734689'
silent! let g:plugs['nvim-treesitter'].commit = 'aebc6cf6bd4675ac86629f516d612ad5288f7868'
silent! let g:plugs['nvim-treesitter-context'].commit = '8d0759eb798fee2e1201b26c3279713ac67c44c2'
silent! let g:plugs['nvim-treesitter-refactor'].commit = '75f5895cc662d61eb919da8050b7a0124400d589'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '41e8d8964e5c874d9ce5e37d00a52f37f218502e'
silent! let g:plugs['plenary.nvim'].commit = '4b7e52044bbb84242158d977a50c4cbcd85070c7'
silent! let g:plugs['telescope-dap.nvim'].commit = 'b4134fff5cbaf3b876e6011212ed60646e56f060'
silent! let g:plugs['telescope.nvim'].commit = '76ea9a898d3307244dce3573392dcf2cc38f340f'
silent! let g:plugs['vim-vsnip'].commit = '8f199ef690ed26dcbb8973d9a6760d1332449ac9'

PlugUpdate!

