@startuml
!theme mars
' !theme materia
' !theme mimeograph
' !theme plain
' !theme toy
<style>
root {
  Margin 30
}
</style>

actor "Node A\n192.168.0.2" as A
queue "NAT A" as NA
participant "Server" as C
queue "NAT B" as NB
actor "Node B\n10.0.0.2" as B

group Discovering IPs and ports

A -> NA: from 192.168.0.2:1194
NA -> C: from x.x.x.x:P
C -> C: store x.x.x.x:P
NA <- C: to: x.x.x.x:P\nno data yet
A <- NA: no data yet

...

B -> NB: from 10.0.0.2:12345
NB -> C: from y.y.y.y:Q
C -> C: store y.y.y.y:Q\nand return\nprivies x.x.x.x:P
note left C
if A will be back,
it will obtain
y.y.y.y:Q in response
end note
NB <- C: to: y.y.y.y:Q\ndata: x.x.x.x:P
B <- NB: data: x.x.x.x:P

end

group Drilling (towards one another)

NB x<- B: "ping" to x.x.x.x:P
NA x<- B: "ping" to x.x.x.x:P
A <- B: "ping" to x.x.x.x:P
A ->x NB: "pong" to y.y.y.y:Q
A -> B: "pong" to y.y.y.y:Q
A <- B: "close" to x.x.x.x:P (with retries too)

note right A: client A finish by close
note left B: client B finish after all tries

end

... start applications on both A and B node ...

A <-> B: hole is punched. Endpoints: x.x.x.x:P and y.y.y.y:Q

@enduml
