version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - nlreturn
    - noinlineerr
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/michurin/warehouse/go/jsonguide
    revive:
      rules:
        - name: exported
          disabled: true
    varnamelen:
      max-distance: 50
    cyclop:
      max-complexity: 25
    gocognit:
      min-complexity: 40
    funlen:
      statements: 50
    nestif:
      min-complexity: 6
    mnd:
      ignored-numbers: [1000, 1000000]
    lll:
      line-length: 160
    staticcheck:
      checks:
        - all
        - -QF1001
  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - path: "_test\\.go$"
        linters:
          - gosec
      - source: "if err == io\\.EOF"
        linters:
          - errorlint
      - source: "fmt\\.Fprint(f|ln)"
        linters:
          - errcheck
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/warehouse/go/jsonguide)
